# Generated by Django 2.2.10 on 2021-05-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['end_date']},
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('ответ текстом', 'text'), ('single_choice', 'single_choice'), ('multiple_choice', 'multiple_choice')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnswerChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='api.Question')),
            ],
        ),
    ]
