# Generated by Django 2.2.10 on 2021-05-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210522_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_id',
        ),
    ]
